### ISSUE TITLE
Response logging for different Content classes

### ISSUE THREAD

**Issue by Kabennsky** [Koriit/ktor-logging#1]
First of all i think thats the only custom Ktor logger on whole github. So props for that, really helps to understand.
I tried implement my own Feature similiar to yours.
I am unable to log the response. If the response is a TextContent or as in your example a ByteArrayContent its easy to log it.
But if your response is a OutputStreamContent i see no way to get the response body.
Have you ever managed to do that?

Btw OutputStreamContent is generate for example when responding with a data class.
I am using Jackson ContentNegotiation for the serialization.

**Comment by Koriit** [comment]
Hello, thank you for checking out my project and leaving a comment. :)

Regarding your problem. Logging streamed content is very tricky. :D You can only read it once, which of course, happens when sending a response or parsing a request. :| So, you need to somehow read every incoming byte and copy it into 2 streams: first for normal request/response processing and second for logging purposes. Fortunately, Ktor Server does it out of the box with [DoubleReceive ](https://ktor.io/docs/double-receive.html) feature. For Ktor Client, I wasn't so lucky, so I had to[ implement that copying myself](https://github.com/Koriit/ktor-client-logging/blob/master/src/main/kotlin/korrit/kotlin/ktor/client/features/logging/ObservedContent.kt#L50) with coroutines which isn't that easy as you have to fight back nasty concurrency issues (channel already closed exceptions and the like).

I also used [Jackson ContentNegotiation](https://ktor.io/docs/jackson.html#register_jackson_converter) and, without any issues, logged request/response payloads with this feature. For huge responses that used Jackson stream builder, I deemed logging undesirable as it would defeat the whole purpose of using streaming response. 

However, that was with Ktor 1.3, so something might have changed in the meantime as the current version is 1.6. 

Since I'm now evangelizing people in my new workplace, I'm slowly going back to Kotlin, and I figured that I need to refresh my libraries. :) So, I'd like to understand your issue better. Also, some sample project or code of your setup would be much appreciated as I could incorporate it in my tests.

**Comment by Kabennsky** [comment]
Thank you very much for your answer. 
The DoubleReceive feature is really nice but it only works for the Request Streams if i got it right.

I build a simple sample [ktor-logging-sample](https://github.com/Kabennsky/ktor-logging-sample) to show you what i try to reach and already reached. I put a ToDo in my KtorServerLogging plugin where i tried to get the body from the subject in the intercepter. But i cant find a way to read any body from the OutputStreamContent, maybe i am intercepting the wrong phase?
There is also a client logger which in my case was feeling much easier to implement.

Also feel free to contact me per mail (see info at my github profile) for a easier way of communication if you want.

**Comment by Koriit** [comment]
Hello @Kabennsky, took me a while but I have some good news for you.

Firstly, I migrated this library to Maven Central and updated it to the latest Kotlin and Ktor versions.

Secondly, it appears that in Ktor 1.4.2 they introduced [a change](https://github.com/ktorio/ktor/compare/1.4.1...1.4.2#diff-d7d32eac960964c0a83d70b439338e409552405a31eda3fa892fb1d54d122a59) in which `JacksonConverter` returns `OutputStreamContent` instead of `TextContent` (a type of `ByteArrayContent`), which of course also broke my code.

To fix the issue, I had to replicate the stream, passing one copy to the logging and another further down the pipeline stream. Fortunately for me, the same problem existed in [ktor-client-logging](https://github.com/Koriit/ktor-client-logging) but for requests so I could reuse the same trick I used there. You can see it in action here:
https://github.com/Koriit/ktor-logging/blob/master/src/main/kotlin/com/korrit/kotlin/ktor/features/logging/Logging.kt#L170
https://github.com/Koriit/ktor-logging/blob/master/src/main/kotlin/com/korrit/kotlin/ktor/features/logging/ObservedContent.kt

Finally, heartfelt thanks for bringing this issue up as it would take a while for me to notice something is amiss because my tests didn't test for this and I don't usually log the payloads.
